const namespaces = {
  a: 'http://schemas.openxmlformats.org/drawingml/2006/main',
  b: 'http://schemas.openxmlformats.org/officeDocument/2006/bibliography',
  cdr: 'http://schemas.openxmlformats.org/drawingml/2006/chartDrawing',
  dc: 'http://purl.org/dc/elements/1.1/',
  dcmitype: 'http://purl.org/dc/dcmitype/',
  dcterms: 'http://purl.org/dc/terms/',
  o: 'urn:schemas-microsoft-com:office:office',
  pic: 'http://schemas.openxmlformats.org/drawingml/2006/picture',
  r: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
  v: 'urn:schemas-microsoft-com:vml',
  ve: 'http://schemas.openxmlformats.org/markup-compatibility/2006',
  vt: 'http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes',
  w: 'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  w10: 'urn:schemas-microsoft-com:office:word',
  wp: 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing',
  wne: 'http://schemas.microsoft.com/office/word/2006/wordml',
  xsd: 'http://www.w3.org/2001/XMLSchema',
  xsi: 'http://www.w3.org/2001/XMLSchema-instance',
  numbering: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering',
  fontTable: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable',
  hyperlinks: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink',
  images: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/image',
  styles: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles',
  headers: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/header',
  footers: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer',
  themes: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme',
  coreProperties: 'http://schemas.openxmlformats.org/package/2006/metadata/core-properties',
  officeDocumentRelation:
    'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument',
  corePropertiesRelation:
    'http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties',
  settingsRelation: 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings',
  webSettingsRelation:
    'http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings',
  sl: 'http://schemas.openxmlformats.org/schemaLibrary/2006/main',
  contentTypes: 'http://schemas.openxmlformats.org/package/2006/content-types',
  relationship: 'http://schemas.openxmlformats.org/package/2006/relationships',
  wpc:"http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas",
  cx:"http://schemas.microsoft.com/office/drawing/2014/chartex",
  cx1:"http://schemas.microsoft.com/office/drawing/2015/9/8/chartex",
  cx2:"http://schemas.microsoft.com/office/drawing/2015/10/21/chartex",
  cx3:"http://schemas.microsoft.com/office/drawing/2016/5/9/chartex",
  cx4:"http://schemas.microsoft.com/office/drawing/2016/5/10/chartex",
  cx5:"http://schemas.microsoft.com/office/drawing/2016/5/11/chartex",
  cx6:"http://schemas.microsoft.com/office/drawing/2016/5/12/chartex",
  cx7:"http://schemas.microsoft.com/office/drawing/2016/5/13/chartex",
  cx8:"http://schemas.microsoft.com/office/drawing/2016/5/14/chartex",
  mc:"http://schemas.openxmlformats.org/markup-compatibility/2006",
  aink:"http://schemas.microsoft.com/office/drawing/2016/ink",
  am3d:"http://schemas.microsoft.com/office/drawing/2017/model3d",
  o:"urn:schemas-microsoft-com:office:office",
  oel:"http://schemas.microsoft.com/office/2019/extlst",
  r:"http://schemas.openxmlformats.org/officeDocument/2006/relationships",
  m:"http://schemas.openxmlformats.org/officeDocument/2006/math",
  v:"urn:schemas-microsoft-com:vml",
  wp14:"http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing",
  wp:"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing",
  w10:"urn:schemas-microsoft-com:office:word",
  w:"http://schemas.openxmlformats.org/wordprocessingml/2006/main",
  w14:"http://schemas.microsoft.com/office/word/2010/wordml",
  w15:"http://schemas.microsoft.com/office/word/2012/wordml",
  w16cex:"http://schemas.microsoft.com/office/word/2018/wordml/cex",
  w16cid:"http://schemas.microsoft.com/office/word/2016/wordml/cid",
  w16:"http://schemas.microsoft.com/office/word/2018/wordml",
  w16du:"http://schemas.microsoft.com/office/word/2023/wordml/word16du",
  w16sdtdh:"http://schemas.microsoft.com/office/word/2020/wordml/sdtdatahash",
  w16sdtfl:"http://schemas.microsoft.com/office/word/2024/wordml/sdtformatlock",
  w16se:"http://schemas.microsoft.com/office/word/2015/wordml/symex",
  wpg:"http://schemas.microsoft.com/office/word/2010/wordprocessingGroup",
  wpi:"http://schemas.microsoft.com/office/word/2010/wordprocessingInk",
  wne:"http://schemas.microsoft.com/office/word/2006/wordml",
  wps:"http://schemas.microsoft.com/office/word/2010/wordprocessingShape",
  Ignorable:"w14 w15 w16se w16cid w16 w16cex w16sdtdh w16sdtfl w16du wp14"
};

export default namespaces;
